name: Maven Integration Tests

on:
  push:
    branches:
      - query-laning-metrics-github-v2

env:
  MVN: mvn -B
  MAVEN_SKIP: -Pskip-static-checks -Ddruid.console.skip=true -Dmaven.javadoc.skip=true
  MAVEN_SKIP_TESTS: -Pskip-tests

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Cat settings.xml
        run: cat settings.xml

      - name: MVN env 1
        run: echo "MVN :${{env.MVN}}"

      - name: MVN env 2
        run: echo "MVN is:$MVN"

      - name: Java version
        run: java -Xmx32m -version

      - name: javac version
        run: javac -J-Xmx32m -version

      - name: mvn version
        run: mvn --version

#      - name: Build with Maven
#        run: mvn clean compile -U -B verify -pl integration-tests -P integration-tests -Dgroups=batch-index -Djvm.runtime=8 -Dit.indexer=middleManager -Pskip-tests -Doverride.config.path=${OVERRIDE_CONFIG_PATH}
