name: Maven Spotbugs Check

on:
  push:
    branches:
      - query-laning-metrics-github

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Export MVN
        run: export MVN="mvn -B"

      - name: Java version
        run: java -Xmx32m -version

      - name: javac version
        run: javac -J-Xmx32m -version

      - name: Build with Maven
        run: ${MVN} spotbugs:check --fail-at-end -pl '!benchmarks'